### ISSUE TITLE
In case of mail error user password gets stored in logfile

### ISSUE THREAD

**Issue by mpw-wwu** [rubenarslan/formr.org#357]
While configurating email sending, I noticed that in case of an error, the user password is stored unencryptedly in the logfile:

```
2018-07-16 08:58:18  Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Xl4-QKKNvj8NYvSxj6YN86LKZg7ArGNgWWJVRMFFyA90TTY2SDBC5Broq5z6rGEJ' for key 'user_code_UNIQUE'
#0 /www/data/PsyTD/formr-produktiv/application/Library/DB.php(287): PDOStatement->execute()
#1 /www/data/PsyTD/formr-produktiv/application/Model/User.php(119): DB->insert('survey_users', Array)
#2 /www/data/PsyTD/formr-produktiv/application/Controller/PublicController.php(136): User->register('matthiaspeterw@...', 'blabla123', '')
#3 /www/data/PsyTD/formr-produktiv/application/Library/Router.php(184): PublicController->registerAction()
#4 /www/data/PsyTD/formr-produktiv/webroot/index.php(42): Router->execute()
#5 {main}
```

**Comment by mpw-wwu** [comment]
This might be fixed by the usage of HiddenStrings.
